config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  resources :gigs

  resources :customers

  root 'tickets#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, :email, :phonenumber, :adress, presence: true
  validates :name, uniqueness: true
  has_many :tickets
  has_many :gigs, :through => :tickets
  accepts_nested_attributes_for :tickets
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  validates :date, :band, :price, uniqueness: true
  has_many :tickets
  has_many :customers, :through => :tickets

  def name
    "#{band} #{date}"
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :customer_id, :gig_id, :paid, presence: true
  belongs_to :customer
  belongs_to :gig
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phonenumber, :adress)
    end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:date, :band, :price)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:customer_id, :gig_id, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/customers/_form.html.haml
= form_for @customer do |f|
  - if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phonenumber
    = f.text_field :phonenumber
  .field
    = f.label :adress
    = f.text_area :adress
  .actions
    = f.submit 'Save'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
%h1 Listing customers

%table
  %tr
    %th Name
    %th Email
    %th Phonenumber
    %th Adress
    %th
    %th
    %th

  - @customers.each do |customer|
    %tr
      %td= customer.name
      %td= customer.email
      %td= customer.phonenumber
      %td= customer.adress
      %td= link_to 'Show', customer
      %td= link_to 'Edit', edit_customer_path(customer)
      %td= link_to 'Destroy', customer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @customer.name
%p
  %b Email:
  = @customer.email
%p
  %b Phonenumber:
  = @customer.phonenumber
%p
  %b Adress:
  = @customer.adress

= link_to 'Edit', edit_customer_path(@customer)
\|
= link_to 'Back', customers_path

app/views/gigs/_form.html.haml
= form_for @gig do |f|
  - if @gig.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gig.errors.count, "error")} prohibited this gig from being saved:"
      %ul
        - @gig.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :band
    = f.text_field :band
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/gigs/edit.html.haml
%h1 Editing gig

= render 'form'

= link_to 'Show', @gig
\|
= link_to 'Back', gigs_path

app/views/gigs/index.html.haml
%h1 Listing gigs

%table
  %tr
    %th Date
    %th Band
    %th Price
    %th
    %th
    %th

  - @gigs.each do |gig|
    %tr
      %td= gig.date
      %td= gig.band
      %td= gig.price
      %td= link_to 'Show', gig
      %td= link_to 'Edit', edit_gig_path(gig)
      %td= link_to 'Destroy', gig, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gig', new_gig_path

app/views/gigs/new.html.haml
%h1 New gig

= render 'form'

= link_to 'Back', gigs_path

app/views/gigs/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @gig.date
%p
  %b Band:
  = @gig.band
%p
  %b Price:
  = @gig.price

= link_to 'Edit', edit_gig_path(@gig)
\|
= link_to 'Back', gigs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.haml
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :customer_id
    = f.select(:customer_id, options_from_collection_for_select(Customer.all, :id, :name),)
  .field
    = f.label :gig_id
    = f.select(:gig_id, options_from_collection_for_select(Gig.all, :id, :band),)
  .field
    = f.label :paid
    = f.check_box :paid
  .actions
    = f.submit 'Save'

app/views/tickets/edit.html.haml
%h1 Editing ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
%h1 Listing tickets

%table
  %tr
    %th Customer
    %th Gig
    %th Paid
    %th
    %th
    %th

  - @tickets.each do |ticket|
    %tr
      %td= link_to ticket.customer.name, ticket.customer
      %td= link_to ticket.gig.band, ticket.gig
      %td= ticket.paid
      %td= link_to 'Show', ticket
      %td= link_to 'Edit', edit_ticket_path(ticket)
      %td= link_to 'Destroy', ticket, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.haml
%h1 New ticket

= render 'form'

= link_to 'Back', tickets_path

app/views/tickets/show.html.haml
%p#notice= notice

%p
  %b Customer:
  = link_to @ticket.customer.name, @ticket.customer
%p
  %b Gig:
  = link_to @ticket.gig.date, @ticket.gig
  = link_to @ticket.gig.band, @ticket.gig
%p
  %b Paid:
  = @ticket.paid

= link_to 'Edit', edit_ticket_path(@ticket)
\|
= link_to 'Back', tickets_path